# Generated by Django 5.2.1 on 2025-06-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=10)),
                ('standard', models.CharField(max_length=2)),
                ('branch', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('responded', 'Responded')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admissions',
            },
        ),
    ]
