# Generated by Django 5.2.1 on 2025-05-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('responded', 'Responded')], default='new', max_length=10),
        ),
    ]
